<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LgbtqMode>false</LgbtqMode>
    <SummerMode>true</SummerMode>
    <HalloweenMode>false</HalloweenMode>
    <ChristmasMode>false</ChristmasMode>
    <ApplicationIcon Condition="'$(LgbtqMode)' == 'true'">icon LGBTQ+.ico</ApplicationIcon>
    <ApplicationIcon Condition="'$(LgbtqMode)' != 'true'">icon.ico</ApplicationIcon>
    <ApplicationIcon Condition="'$(SummerMode)' == 'true'">icon Summer.ico</ApplicationIcon>
    <ApplicationIcon Condition="'$(HalloweenMode)' == 'true'">icon Halloween.ico</ApplicationIcon>
    <ApplicationIcon Condition="'$(ChristmasMode)' == 'true'">icon Christmas.ico</ApplicationIcon>
    <DefineConstants Condition="'$(LgbtqMode)' == 'true'">$(DefineConstants);LGBTQ_MODE</DefineConstants>
    <DefineConstants Condition="'$(SummerMode)' == 'true'">$(DefineConstants);SUMMER_MODE</DefineConstants>
    <DefineConstants Condition="'$(HalloweenMode)' == 'true'">$(DefineConstants);HALLOWEEN_MODE</DefineConstants>
    <DefineConstants Condition="'$(ChristmasMode)' == 'true'">$(DefineConstants);CHRISTMAS_MODE</DefineConstants>
    <AssemblyName>PlaytimeSpeedLauncher</AssemblyName>
    <RootNamespace>SpeedrunLauncher</RootNamespace>
    <Version>2.0.7</Version>
    <Authors>An Average Developer</Authors>
    <Product>PlaytimeSpeedLauncher</Product>
    <Description>A Launcher for Speedruners of Poppy Playtime</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=.</PathMap>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="YoutubeExplode" Version="6.*" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.16" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="icon.ico">
      <LogicalName>default_icon</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icon LGBTQ+.ico">
      <LogicalName>lgbtq_icon</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icon Summer.ico">
      <LogicalName>summer_icon</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icon Halloween.ico">
      <LogicalName>halloween_icon</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icon Christmas.ico">
      <LogicalName>christmas_icon</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\**">
      <LogicalName>assets___%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Transalations\**">
      <LogicalName>translations___%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
